#!/bin/sh
bib=$(cat | bibtool -R -r biblatex)
key=$(echo $bib | pcregrep -M -o "^@.*," | pcregrep -M -o "(?<=\{).*(?=,)")

if grep -Fq $key ~/Documents/myBib/main.bib
then
    echo "${key} found in main.bib. Abort..."
    exit 1
else
    echo $bib | bibtool -R -r biblatex -i /dev/stdin ~/Documents/myBib/main.bib -o ~/Documents/myBib/main.bib 
    reminders add Lesen "Read @${key}"
fi
