#! /bin/sh

BIBKEYFMT='-- fmt.et.al={} -f "{%N(shortauthor) # %-1n(author) # %-1n(editor) # %-1n(bookauthor) # ohneAutor }_{%-1T(title) # %-1T(booktitle) # ohneTitel}_{%+4d(year) # ohneJahr}" -r biblatex  main.bib'


get_bib() {
    queryresult=(curl -s "https://api.crossref.org/works/$1/transform/application/x-bibtex" -w "\\n")

}


check_file() {
    find ~/Documents/Sci-Bib/. | grep -i -q ${1}
    if [ $? -eq 0 ]
    then
            old_file=$(find ~/Documents/Sci-Bib/. | grep -i ${1})
            get_old_info $old_file
            mv $old_file "old""$key"".txt"
            make_file
            if [ -z ${old_pdf+x} ]; then : ; else mv "$old_pdf" "$key"".pdf" ; fi
            exit 1
    else
            :   
    fi
}

pdf2doi () {
        doi=$(pdfinfo "$1" | grep -io "doi:.*") ||
        doi=(pdftotext "$1" - | pcregrep -M -o "\b(10[.][0-9]{4,}(?:[.][0-9]+)*/(?:(?![\"&\'<>])\S)+)\b" | head -n 1) ||
        exit 1
        old_pdf=(echo $1)
        old_info_md=$(echo $old_pdf | pcregrep -o "^.*(?=\.)")
        get_bib
        check_file "$old_info_md"".md"
        check_file "$key"".md"
        make_file
        mv "$old_pdf" "$key"".pdf" 
        exit 1
}
