#!/bin/sh
key=$(echo $1 | tr -d .pdf)
cat $HOME/Documents/myBib/main.bib | grep -wq "$key"
if [ $? -eq 1 ]
then
    echo "$key key wasn't found in main.bib. Abort..."
    exit 1
else
    echo "$key was found in main.bib. Continue..."
fi
real_page=$(cat $HOME/Documents/myBib/main.bib | pcregrep -o -M "(?<=$key)(.|\n)*" | pcregrep -v -M "^\}(.|\n)*" | pcregrep -o "Pages\s+=\s\{\d+" | pcregrep -o "\d+" )
real_page_minus=$(($real_page - 1))

notes=$(skimnotes get -format text "${key}.pdf" - )
echo "$notes" | while read -d "*" line
do
    pdf_page=$(echo $line | pcregrep -o "(?<=page\s)\d*")
    page=$(expr $real_page_minus + $pdf_page)
    if [[ $line == *'Hervorhebung'* ]]; then 
        inner_content=$(echo $line | pcregrep -M -o "(?<=\d\s).*")
        cite_string=$(echo "'${inner_content}' [@${key}, S. ${page}]")
        echo $cite_string
    elif [[ $line == *'Fixiert'* ]]; then 
        tags=$(echo "$line" | sed -n 2p)
        content=$(echo "$line" | sed '1,3d')
    fi     
done

