#!/bin/sh
use_doi=false
use_ayt=false
use_bib=false
while getopts bd:a:y:t: opt; do
    case $opt in
        b)
            use_bib=true
            use_ayt=false
            use_doi=false
            ;;
        d)
            doi=$OPTARG
            use_doi=true
            use_ayt=false
            use_bib=false
            ;;
        a)
            author=$OPTARG
            use_ayt=true
            use_doi=false
            use_bib=false
            ;;
        y)
            year=$OPTARG
            use_ayt=true
            use_doi=false
            use_bib=false
            ;;
        t)
            title=$OPTARG
            use_ayt=true
            use_doi=false
            use_bib=false
            ;;
        ?)
            exit 1
            ;;
    esac
done

shift $((OPTIND-1))


move_file() {
    find ~/Documents/myBib/pdfs/$1.pdf
    if [ $? -eq 1 ]
    then
        mv "${2}" "$HOME/Documents/myBib/pdfs/${1}.pdf"
        echo "in function 2 ${2}"
    else
            echo "${1}.pdf was found. Abort..."
            exit 1
    fi
}

if [ "$use_doi" = true ]
then
    bib=$(doi2bib $doi | bibtool -R -r biblatex)
    key=$(echo $bib | pcregrep -M -o "^@[^\,]*" | pcregrep -M -o "(?<=\{).*")
    echo $bib | bib2myBib
    move_file $key $1
    exit 0
elif [ "$use_ayt" = true ]
then
    #pass over to bib2myBib
    string="@article{articlekey, Author = {${author}, Title = {${title}}, Year = ${year}}}"
    bib=$(echo $string | bibtool -R -r biblatex)
    key=$(echo $bib | pcregrep -M -o "^@[^\,]*" | pcregrep -M -o "(?<=\{).*")
    echo $bib | bib2myBib
    move_file $key $1
elif [ "$use_bib" = true ]
then
    bib=$(pbpaste | bibtool -R -r biblatex)
    key=$(echo $bib | pcregrep -M -o "^@[^\,]*" | pcregrep -M -o "(?<=\{).*")
    if [[ "$key" == "" ]]; then
        exit 1
    fi
    echo $bib | bib2myBib
    move_file $key $1
else
    doi=$(pdf2doi $1)
    bib=$(doi2bib $doi | bibtool -R -r biblatex)
    key=$(echo $bib | pcregrep -M -o "^@[^\,]*" | pcregrep -M -o "(?<=\{).*")
    if [[ "$key" == "" ]]; then
        exit 1
    fi
    echo $bib | bib2myBib
    move_file $key $1
fi
