#!/bin/bash

while getopts c:d: opt; do
    case $opt in
        c)
            citekey=$OPTARG
            ;;
        d)
            doi=$OPTARG
            ;;
        ?)
            echo "usage: "
            exit 1
            ;;
    esac
done

shift $((OPTIND-1))



    
check_file() {
    find ~/Documents/Sci-Bib/. | grep -i -q ${1}
    if [ $? -eq 0 ]
    then
            old_file=$(find ~/Documents/Sci-Bib/. | grep -i ${1})
            get_old_info $old_file
            mv $old_file "old""$key"".txt"
            make_file
            if [ -z ${old_pdf+x} ]; then : ; else mv "$old_pdf" "$key"".pdf" ; fi
            exit 1
    else
            :   
    fi
}


