#!/bin/sh
use_all=false
while getopts "a" opt; do
    case $opt in
        a)
            use_all=true
            ;;
        ?)
            echo "scipt usage: "
            exit 1
            ;;
    esac
done

shift $((OPTIND - 1))

if [ "$use_all" = true ] ; then
    for FILE in "$@"; do
    
        if [ -d "$FILE" ];
        then
            echo "Skipping directory $FILE" >&2
            continue
        fi
    
        dois=$(pdftotext "$FILE" - | pcregrep -i -o '10.\d{4,9}\/[-._;()\/:A-Z0-9]+' | tr [:space:] '\n' | sed 's/\.$//' )
            for doi in $dois
            do
                doi2bib $doi
            done
    done 
    exit 0
fi

for FILE in "$@"; do
    if [ -d "$FILE" ];
    then
        echo "Skipping directory $FILE" >&2
        continue
    fi
    doi=$(pdfinfo "$FILE" | pcregrep -i -o '10.\d{4,9}\/[-._;()\/:A-Z0-9]+' | tr [:space:] '\n' | sed 's/\.$//' | head -n 1)
    if [[ $doi == "" ]]; then
        doi=$(pdftotext -l 3 "$FILE" - | pcregrep -i -o '10.\d{4,9}\/[-._;()\/:A-Z0-9]+' | tr [:space:] '\n' | sed 's/\.$//' | head -n 1)
    fi
    if [[ $doi == "" ]]; then
        doi=$(pdftotext "$FILE" - | pcregrep -i -o '10.\d{4,9}\/[-._;()\/:A-Z0-9]+' | tr [:space:] '\n' | sed 's/\.$//' | tail -n 1) 
    fi
    echo $doi
done

exit 0
