export LANG="en_US.UTF-8"
export EDITOR="nvim"
export PATH="$PATH:$HOME/.scripts"
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/bin:/usr/local/bin:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
